Document: mobile-jolokia-client
Title: Debian mobile-jolokia-client Manual
Author: <insert document author here>
Abstract: This manual describes what mobile-jolokia-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mobile-jolokia-client/mobile-jolokia-client.sgml.gz

Format: postscript
Files: /usr/share/doc/mobile-jolokia-client/mobile-jolokia-client.ps.gz

Format: text
Files: /usr/share/doc/mobile-jolokia-client/mobile-jolokia-client.text.gz

Format: HTML
Index: /usr/share/doc/mobile-jolokia-client/html/index.html
Files: /usr/share/doc/mobile-jolokia-client/html/*.html
